/**
 * \file license.cpp
 * \brief Implementation of the License dialog.
 *
 * Defines the methods for the License dialog, which displays configuration
 * and license information retrieved from the main window.
 *
 * \author Constantin
 */

#include "license.h"  // Include the header file for the License dialog class.

#include <QCoreApplication>  // For applicationDirPath()
#include <QDir>              // For path manipulation
#include "mainwindow.h"  // Include the header file for the MainWindow class.
#include "ui_license.h"  // Include the UI header file generated by Qt Designer.

namespace {
MainWindow* mainwindow = nullptr;
}

/**
 * \brief Constructs the License dialog.
 *
 * Initializes the License dialog, sets up the UI defined in Ui::License,
 * applies translations to UI elements, and connects the close button
 * signal to the onCloseClicked slot.
 *
 * \param parent Pointer to the parent QWidget.
 */
License::License(QWidget* parent) : QDialog(parent), ui(new Ui::Licence) {

    ui->setupUi(this);                               ///< Set up the user interface.
    mainwindow = dynamic_cast<MainWindow*>(parent);  ///< Cast parent to MainWindow pointer.

    // Validate cast succeeded - critical for safe operation
    if (!mainwindow) {
        qCritical() << "License::License: Failed to cast parent to MainWindow*";
        // Cannot continue without valid MainWindow pointer - would cause crash
        return;
    }

    Translate();                                     ///< Translate UI elements.

    // Force small font size for ELCOST info label using stylesheet
    ui->lbElcostInfo->setStyleSheet("QLabel { font-size: 9px; font-family: Verdana; font-style: italic; }");

    // Connect close button click signal to onCloseClicked slot
    connect(ui->pbClose, &QPushButton::clicked, this, &License::onCloseClicked);
}

/**
 * \brief Updates UI elements in the License dialog with localized text.
 *
 * Translates and sets the text for QLabel and QPushButton elements
 * in the License dialog using Qt's tr() mechanism, ensuring all
 * UI elements display text according to the application's current locale.
 */
void License::Translate() {
    // Retranslate UI elements from .ui file (tooltips, etc.)
    ui->retranslateUi(this);

    setWindowTitle(tr("WStreamLab - License"));                 ///< Set the window title.
    ui->groupBox->setTitle(tr("License Information"));          ///< Set text for group box.
    ui->lbCertificate->setText(tr("Certificate:"));             ///< Set text for certificate label.
    ui->lbDensity->setText(tr("Water density at 20 °C:"));      ///< Set text for water density label.
    ui->lbDensityUnit->setText(tr("[kg/m³]"));                  ///< Set text for density unit label.
    ui->lbArchive->setText(tr("Archive folder:"));              ///< Set text for archive folder label.
    ui->lbCompany->setText(tr("Company:"));                     ///< Set text for company label.
    ui->lbVolumeCorrection->setText(tr("Volume correction:"));  ///< Set text for volume correction label.
    ui->lbChecksum->setText(tr("Checksum:"));                   ///< Set text for checksum label.
    ui->lbFileLocation->setText(tr("Configuration file:"));     ///< Set text for file location label.
    ui->lbElcostInfo->setText(tr("Note: Configuration data can only be modified by regenerating the certificate through ELCOST."));  ///< Set info text.
    ui->pbClose->setText(tr("Close"));                          ///< Set text for close button.
}

/**
 * \brief Handles the License dialog show event.
 *
 * Overrides QWidget::showEvent() to update displayed values based on
 * the configuration options stored in the MainWindow. Sets the text
 * of QLabel widgets using specific keys from the configuration,
 * converting values from std::string to QString.
 *
 * \param event Pointer to the QShowEvent.
 */
void License::showEvent(QShowEvent* event) {
    QWidget::showEvent(event);  ///< Call base class showEvent.

    if (!mainwindow)
        return;

    // Set initial focus to the close button
    ui->pbClose->setFocus();

    // Update UI elements with values from MainWindow's options configuration
    ui->lbCompanyValue->setText(QString::fromStdString(mainwindow->optionsConfiguration["company"]));
    ui->lbCertificateValue->setText(QString::fromStdString(mainwindow->optionsConfiguration["certificate"]));
    ui->lbArchiveValue->setText(QString::fromStdString(mainwindow->optionsConfiguration["archive"]));

    std::string volumeCorrectionType = mainwindow->optionsConfiguration["volume_correction"];
    if (volumeCorrectionType == "CLASSIC_VOLUME_CORRECTION")
        volumeCorrectionType = "CLASSIC VOLUME CORRECTION";
    else if (volumeCorrectionType == "INM_VOLUME_CORRECTION")
        volumeCorrectionType = "INM VOLUME CORRECTION";
    else if (volumeCorrectionType == "ELCOST_VOLUME_CORRECTION")
        volumeCorrectionType = "ELCOST VOLUME CORRECTION";
    else
        volumeCorrectionType = "UNKNOWN";
    ui->lbVolumeCorrectionValue->setText(QString::fromStdString(volumeCorrectionType));

    ui->lbDensityValue->setText(QString::fromStdString(mainwindow->optionsConfiguration["density_20"]));
    ui->lbChecksumValue->setText(QString::fromStdString(mainwindow->optionsConfiguration["control"]));

    // Set configuration file name only (without path)
    ui->lbFileLocationValue->setText("watermeters.conf");
}

/**
 * \brief Slot triggered when the close button is clicked.
 *
 * Connected to the clicked signal of pbClose. Hides the License dialog
 * by calling hide() when the button is pressed.
 */
void License::onCloseClicked() {
    this->hide();  ///< Hide the License dialog.
}

/**
 * \brief Destroys the License dialog.
 *
 * Deletes the `ui` object to release resources allocated for
 * the user interface when the License dialog is destroyed.
 */
License::~License() {
    delete ui;  ///< Delete the user interface object.
}
